# Generated by Django 3.1.5 on 2021-02-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210130_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, to='core.Student'),
        ),
    ]
