# Generated by Django 3.1.5 on 2021-02-09 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210209_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='students',
            field=models.ManyToManyField(blank=True, to='core.Student'),
        ),
    ]
