# Generated by Django 3.1.5 on 2021-02-13 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourcecenter', '0011_file_delete_id'),
        ('core', '0006_auto_20210211_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='files',
            field=models.ManyToManyField(to='resourcecenter.File'),
        ),
    ]
