# Generated by Django 3.1.5 on 2021-02-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_student_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_resourcecenter_admin',
            field=models.BooleanField(default=False),
        ),
    ]
