# Generated by Django 3.1.5 on 2021-02-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourcecenter', '0014_auto_20210215_1029'),
        ('core', '0008_student_is_resourcecenter_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='files',
            field=models.ManyToManyField(blank=True, to='resourcecenter.File'),
        ),
    ]
