# Generated by Django 3.1.5 on 2021-01-30 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourcecenter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='description',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='semester',
            field=models.CharField(blank=True, choices=[('1', 'First Semester'), ('2', 'Second Semester'), ('3', 'Not Applicable')], max_length=1, null=True),
        ),
    ]
