# Generated by Django 3.1.5 on 2021-01-30 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourcecenter', '0002_auto_20210130_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='uploader',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
