# Generated by Django 3.1.5 on 2021-02-08 03:19

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resourcecenter', '0003_auto_20210130_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='file.name'),
        ),
    ]
