# Generated by Django 3.1.5 on 2021-02-09 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourcecenter', '0010_nonacademiclevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='delete_id',
            field=models.IntegerField(default=199999999),
            preserve_default=False,
        ),
    ]
