# Generated by Django 3.1.5 on 2021-02-15 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resourcecenter', '0012_reports'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reports',
            new_name='Report',
        ),
    ]
