# Generated by Django 3.1.5 on 2021-05-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourcecenter', '0016_file_file_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traffic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('traffic', models.IntegerField()),
            ],
        ),
    ]
