# Generated by Django 3.1.5 on 2021-05-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourcecenter', '0017_traffic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traffic',
            name='traffic',
            field=models.IntegerField(default=0),
        ),
    ]
